name: deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-source
        uses: actions/checkout@v2
        with:
          path: source
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm
      - name: build
        run: |
          cd source
          npm ci
          npm run build
          cd ..
      - name: checkout-build
        uses: actions/checkout@v2
        with:
          repository: syy1125/syy1125.github.io
          token: ${{ secrets.GH_PAGES_PAT }}
          path: build
      - name: export
        run: cp -r ./source/build/* ./build
      - name: deploy
        run: |
          cd build
          git config user.name ${GITHUB_ACTOR}
          git add .
          git commit -m ${GITHUB_REF#refs/tags/}
          git push
